#!/usr/bin/env bash
#
# reproduce_all.sh -- one-command, end-to-end regeneration of every tracked
# artifact, followed by the manuscript build and a manifest check. This makes the
# claim "every result, table, and figure is regenerated by the supplied code"
# literally true through a single documented workflow.
#
# It runs each producing script with the SAME canonical commands documented in the
# README and RELEASE_MANIFEST.md, and places outputs directly in the tracked
# locations (results/ and manuscript/figures/).
#
# Usage:
#   ./reproduce_all.sh                 # full run (production MC ~1-1.5 h on 2 cores)
#   FAST=1 ./reproduce_all.sh          # small-N smoke run (minutes; NOT the frozen values)
#   SKIP_INVIVO=1 ./reproduce_all.sh   # skip the in-vivo pipeline (needs MNE + the dataset)
#
# Environment:
#   ANALYSIS_ROUND   release label recorded in provenance (default: local)
#   GIT_COMMIT       Git SHA recorded in provenance (default: auto-detected)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"
ROUND="${ANALYSIS_ROUND:-local}"
COMMIT="${GIT_COMMIT:-$(git rev-parse --short HEAD 2>/dev/null || echo unknown)}"
export ANALYSIS_ROUND="$ROUND"

if [ "${FAST:-0}" = "1" ]; then
  NPROD=100000; NROB=40000; echo "[FAST] smoke run: N_prod=$NPROD N_rob=$NROB (NOT the frozen values)"
else
  NPROD=2000000; NROB=500000
fi

echo "== 1/6  Production forward model (mc_production.py) =="
python code/mc_production.py -N "$NPROD" --batches 16 --thin_csf_N "$NPROD" \
  --out code/fcortex_production --git_commit "$COMMIT" --analysis_round "$ROUND"
cp code/fcortex_production.json code/fcortex_production.csv results/

echo "== 2/6  Secondary robustness sweeps (mc_robustness_sweeps.py) =="
python code/mc_robustness_sweeps.py -N "$NROB" --seed 1 \
  --git_commit "$COMMIT" --analysis_round "$ROUND" \
  --out results/robustness_secondary.json

echo "== 3/6  Homogeneous-limit fluence validation (validate_homogeneous_fluence.py) =="
python code/validate_homogeneous_fluence.py \
  --git_commit "$COMMIT" --analysis_round "$ROUND" \
  --out results/homogeneous_fluence_validation.json

echo "== 4/6  Synthetic validation (figures 1-3, multiseed) =="
( cd code && python fnirs_kappa_synthetic_validation.py )
cp code/figure1_timeseries.png code/figure2_summary.png code/figure3_robustness.png manuscript/figures/
cp code/multiseed_operating_regime.json results/

if [ "${SKIP_INVIVO:-0}" != "1" ]; then
  echo "== 5/6  In-vivo pipeline (figures 4-7, real-data summary) =="
  if [ "${RELEASE:-0}" = "1" ]; then
    # RELEASE mode: the in-vivo step MUST succeed. A failure here (missing MNE or
    # dataset) would otherwise leave the previous, now-stale real-data outputs in
    # place and let them survive into a release build -- exactly the release-
    # integrity hazard we are guarding against. Fail hard instead.
    ( cd code && python fnirs_kappa_realdata_v2.py )
  else
    ( cd code && python fnirs_kappa_realdata_v2.py ) || \
      echo "[warn] in-vivo pipeline failed (needs MNE + the pinned Zenodo dataset); skipping."
  fi
  for f in figure4_realdata_timeseries figure5_realdata_hrf figure6_realdata_summary figure7_group_block_average; do
    [ -f "code/$f.png" ] && cp "code/$f.png" manuscript/figures/ || true
  done
  [ -f code/realdata_v2_summary.json ] && cp code/realdata_v2_summary.json results/ || true
elif [ "${RELEASE:-0}" = "1" ]; then
  echo "[fatal] SKIP_INVIVO=1 is not allowed in RELEASE mode (would ship stale real-data outputs)." >&2
  exit 1
else
  echo "== 5/6  In-vivo pipeline SKIPPED (SKIP_INVIVO=1) =="
fi

echo "== 6/6  Build manuscript + pedagogical guide + verify manifest =="
# Use latexmk if available (it iterates pdflatex until labels/refs converge);
# otherwise fall back to THREE explicit pdflatex passes -- cross-references and
# the supplementary \theHtable anchors only stabilise on the third pass, so two
# passes can leave stale labels.
build_latex () {  # $1 = directory, $2 = .tex file
  ( cd "$1" && \
    if command -v latexmk >/dev/null 2>&1; then \
      latexmk -pdf -interaction=nonstopmode "$2" >/dev/null; \
    else \
      pdflatex -interaction=nonstopmode "$2" >/dev/null && \
      pdflatex -interaction=nonstopmode "$2" >/dev/null && \
      pdflatex -interaction=nonstopmode "$2" >/dev/null; \
    fi )
}
build_latex manuscript main.tex
# Rebuild the pedagogical guide PDF from its source too, so EVERY tracked PDF is
# regenerated (not just the manuscript) and the release is genuinely turnkey.
build_latex supplementary fNIRS_Kappa_Pedagogical_Guide.tex
python - <<'PY'
import hashlib, re, os
root = os.path.dirname(os.path.abspath("reproduce_all.sh"))
man = os.path.join(root, "RELEASE_MANIFEST.md")
if not os.path.exists(man):
    print("[manifest] RELEASE_MANIFEST.md not found; skipping verification"); raise SystemExit
ok = bad = 0
for line in open(man):
    m = re.match(r"\|\s*`([0-9a-f]{64})`\s*\|\s*\d+\s*\|\s*`([^`]+)`\s*\|", line)
    if not m: continue
    sha, path = m.group(1), m.group(2)
    fp = os.path.join(root, path)
    if not os.path.exists(fp):
        print(f"[manifest] MISSING {path}"); bad += 1; continue
    got = hashlib.sha256(open(fp, "rb").read()).hexdigest()
    if got == sha: ok += 1
    else: print(f"[manifest] CHANGED {path}"); bad += 1
print(f"[manifest] {ok} files match; {bad} changed/missing "
      f"(changes are expected after regenerating with a different seed/round).")
PY

if [ "${RELEASE:-0}" = "1" ]; then
  echo "== RELEASE: regenerate manifest from the freshly built tree =="
  python code/make_release_manifest.py
fi
echo "== DONE =="
